services:
  invoice-app-frontend:
    container_name: invoice-app-frontend-container
    build: .
    image: invoice-app-frontend:v1
    ports:
     - 80:80
    expose: 
     - 80
    networks:
     - internalnet
    
networks:
  internalnet:
    driver: bridge
